# Generated by Django 4.2.4 on 2023-09-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_update_at_alter_post_create_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="update_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(),
        ),
    ]
