# Generated by Django 4.2.4 on 2023-09-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_update_at_alter_post_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
