# Generated by Django 4.2.6 on 2023-10-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="create_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="head_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="update_at",
        ),
    ]
